export const VIRTUAL_STUDY_LOAD_REQUESTED = 'VIRTUAL_STUDY_LOAD_REQUESTED';
export const VIRTUAL_STUDY_LOAD_SUCCESS = 'VIRTUAL_STUDY_LOAD_SUCCESS';
export const VIRTUAL_STUDY_LOAD_FAILURE = 'VIRTUAL_STUDY_LOAD_FAILURE';
export const SET_ACTIVE_INDEX = 'SET_ACTIVE_INDEX';
export const SET_SQONS = 'SET_SQONS';
export const SET_VIRTUAL_STUDY_ID = 'SET_VIRTUAL_STUDY_ID';
