export const FETCH_VIRTUAL_STUDIES_REQUESTED = 'FETCH_VIRTUAL_STUDIES_REQUESTED';
export const FETCH_VIRTUAL_STUDIES_SUCCESS = 'FETCH_VIRTUAL_STUDIES_SUCCESS';
export const FETCH_VIRTUAL_STUDIES_FAILURE = 'FETCH_VIRTUAL_STUDIES_FAILURE';

export const VIRTUAL_STUDY_LOAD_REQUESTED = 'VIRTUAL_STUDY_LOAD_REQUESTED';
export const VIRTUAL_STUDY_LOAD_SUCCESS = 'VIRTUAL_STUDY_LOAD_SUCCESS';
export const VIRTUAL_STUDY_LOAD_FAILURE = 'VIRTUAL_STUDY_LOAD_FAILURE';

export const VIRTUAL_STUDY_SAVE_REQUESTED = 'VIRTUAL_STUDY_SAVE_REQUESTED';
export const VIRTUAL_STUDY_SAVE_SUCCESS = 'VIRTUAL_STUDY_SAVE_SUCCESS';
export const VIRTUAL_STUDY_SAVE_FAILURE = 'VIRTUAL_STUDY_SAVE_FAILURE';

export const VIRTUAL_STUDY_DELETE_REQUESTED = 'VIRTUAL_STUDY_DELETE_REQUESTED';
export const VIRTUAL_STUDY_DELETE_SUCCESS = 'VIRTUAL_STUDY_DELETE_SUCCESS';
export const VIRTUAL_STUDY_DELETE_FAILURE = 'VIRTUAL_STUDY_DELETE_FAILURE';
export const VIRTUAL_STUDY_CLEAN_ERROR = 'VIRTUAL_STUDY_CLEAN_ERROR';
export const ADD_TERM_TO_CURRENT_VIRTUAL_STUDY = 'ADD_TERM_TO_CURRENT_VIRTUAL_STUDY';

export const VIRTUAL_STUDY_RESET = 'VIRTUAL_STUDY_RESET';

export const SET_ACTIVE_INDEX = 'SET_ACTIVE_INDEX';
export const SET_SQONS = 'SET_SQONS';
export const SET_SELECTION_SQONS = 'SET_SELECTION_SQONS';
export const SET_VIRTUAL_STUDY_ID = 'SET_VIRTUAL_STUDY_ID';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';
export const LOGIN_FAILURE = 'LOGIN_FAILURE';
export const LOGOUT = 'LOGOUT';

export const REQUEST_PROFILE = 'REQUEST_PROFILE';
export const RECEIVE_PROFILE = 'RECEIVE_PROFILE';
export const FAILURE_PROFILE = 'FAILURE_PROFILE';
export const REQUEST_PROFILE_UPDATE = 'REQUEST_PROFILE_UPDATE';
export const FAILURE_UPDATE = 'FAILURE_UPDATE';
export const UPDATE_USER_SUCCESS = 'UPDATE_USER_SUCCEESS';
export const DELETE_PROFILE = 'DELETE_PROFILE';
export const REQUEST_IS_PUBLIC_TOGGLE = 'REQUEST_IS_PUBLIC_TOGGLE';
export const RECEIVE_IS_PUBLIC_TOGGLE = 'RECEIVE_IS_PUBLIC_TOGGLE';
export const FAILURE_IS_PUBLIC_TOGGLE = 'FAILURE_IS_PUBLIC_TOGGLE';
export const REQUEST_IS_ACTIVE_TOGGLE = 'REQUEST_IS_ACTIVE_TOGGLE';
export const RECEIVE_IS_ACTIVE_TOGGLE = 'RECEIVE_IS_ACTIVE_TOGGLE';
export const FAILURE_IS_ACTIVE_TOGGLE = 'FAILURE_IS_ACTIVE_TOGGLE';
export const CLEAN_ERRORS = 'CLEAN_ERRORS';
export const REQUEST_SUBSCRIBE_USER = 'SUBSCRIBE_USER';
export const FAILURE_SUBSCRIBE_USER = 'SUBSCRIBE_USER';

export const ENABLE_FEATURE = 'ENABLE_FEATURE';
