export const LOAD_VIRTUAL_STUDY = 'LOAD_VIRTUAL_STUDY';
export const SET_ACTIVE_INDEX = 'SET_ACTIVE_INDEX';
export const SET_SQONS = 'SET_SQONS';
export const SET_VIRTUAL_STUDY_ID = 'SET_VIRTUAL_STUDY_ID';
