export const FETCH_VIRTUAL_STUDIES_REQUESTED = 'FETCH_VIRTUAL_STUDIES_REQUESTED';
export const FETCH_VIRTUAL_STUDIES_SUCCESS = 'FETCH_VIRTUAL_STUDIES_SUCCESS';
export const FETCH_VIRTUAL_STUDIES_FAILURE = 'FETCH_VIRTUAL_STUDIES_FAILURE';

export const VIRTUAL_STUDY_LOAD_REQUESTED = 'VIRTUAL_STUDY_LOAD_REQUESTED';
export const VIRTUAL_STUDY_LOAD_SUCCESS = 'VIRTUAL_STUDY_LOAD_SUCCESS';
export const VIRTUAL_STUDY_LOAD_FAILURE = 'VIRTUAL_STUDY_LOAD_FAILURE';

export const VIRTUAL_STUDY_SAVE_REQUESTED = 'VIRTUAL_STUDY_SAVE_REQUESTED';
export const VIRTUAL_STUDY_SAVE_SUCCESS = 'VIRTUAL_STUDY_SAVE_SUCCESS';
export const VIRTUAL_STUDY_SAVE_FAILURE = 'VIRTUAL_STUDY_SAVE_FAILURE';

export const VIRTUAL_STUDY_DELETE_REQUESTED = 'VIRTUAL_STUDY_DELETE_REQUESTED';
export const VIRTUAL_STUDY_DELETE_SUCCESS = 'VIRTUAL_STUDY_DELETE_SUCCESS';
export const VIRTUAL_STUDY_DELETE_FAILURE = 'VIRTUAL_STUDY_DELETE_FAILURE';
export const VIRTUAL_STUDY_CLEAN_ERROR = 'VIRTUAL_STUDY_CLEAN_ERROR';
export const ADD_TERM_TO_CURRENT_VIRTUAL_STUDY = 'ADD_TERM_TO_CURRENT_VIRTUAL_STUDY';

export const VIRTUAL_STUDY_RESET = 'VIRTUAL_STUDY_RESET';

export const SET_ACTIVE_INDEX = 'SET_ACTIVE_INDEX';
export const SET_SQONS = 'SET_SQONS';
export const SET_VIRTUAL_STUDY_ID = 'SET_VIRTUAL_STUDY_ID';
