export const infoBoxMock = [
  { value: 340000, description: 'Total Reads' },
  { value: 477, description: 'Max Insert Size' },
  { value: 245, description: 'Mean Depth' },
  { value: 287, description: 'Mean Insert Size' },
  { value: 304, description: 'Mean Read Length' },
];

export const mockData = [
  {
    particpantId: 'PT_JPHXHZFZ',
    externalId: 78724,
    studyName: 'Congential Heart Defect',
    proband: 'no',
    biospecimenId: 'BS_42425',
    analyteType: 'DNA',
    tissueType: 'normal',
    ageAtSampleAcquisition: '40 years 4 days',
  },
  {
    particpantId: 'PT_JPHXHZFZ',
    externalId: 78724,
    studyName: 'Congential Heart Defect',
    proband: 'no',
    biospecimenId: 'BS_42425',
    analyteType: 'DNA',
    tissueType: 'normal',
    ageAtSampleAcquisition: '40 years 4 days',
  },
  {
    particpantId: 'PT_JPHXHZFZ',
    externalId: 78724,
    studyName: 'Congential Heart Defect',
    proband: 'no',
    biospecimenId: 'BS_42425',
    analyteType: 'DNA',
    tissueType: 'normal',
    ageAtSampleAcquisition: '40 years 4 days',
  },
  {
    particpantId: 'PT_JPHXHZFZ',
    externalId: 78724,
    studyName: 'Congential Heart Defect',
    proband: 'no',
    biospecimenId: 'BS_42425',
    analyteType: 'DNA',
    tissueType: 'normal',
    ageAtSampleAcquisition: '40 years 4 days',
  },
  {
    particpantId: 'PT_JPHXHZFZ',
    externalId: 78724,
    studyName: 'Congential Heart Defect',
    proband: 'no',
    biospecimenId: 'BS_42425',
    analyteType: 'DNA',
    tissueType: 'normal',
    ageAtSampleAcquisition: '40 years 4 days',
  },
  {
    particpantId: 'PT_JPHXHZFZ',
    externalId: 78724,
    studyName: 'Congential Heart Defect',
    proband: 'no',
    biospecimenId: 'BS_42425',
    analyteType: 'DNA',
    tissueType: 'normal',
    ageAtSampleAcquisition: '40 years 4 days',
  },
  {
    particpantId: 'PT_JPHXHZFZ',
    externalId: 78724,
    studyName: 'Congential Heart Defect',
    proband: 'no',
    biospecimenId: 'BS_42425',
    analyteType: 'DNA',
    tissueType: 'normal',
    ageAtSampleAcquisition: '40 years 4 days',
  },
  {
    particpantId: 'PT_JPHXHZFZ',
    externalId: 78724,
    studyName: 'Congential Heart Defect',
    proband: 'no',
    biospecimenId: 'BS_42425',
    analyteType: 'DNA',
    tissueType: 'normal',
    ageAtSampleAcquisition: '40 years 4 days',
  },
  {
    particpantId: 'PT_JPHXHZFZ',
    externalId: 78724,
    studyName: 'Congential Heart Defect',
    proband: 'no',
    biospecimenId: 'BS_42425',
    analyteType: 'DNA',
    tissueType: 'normal',
    ageAtSampleAcquisition: '40 years 4 days',
  },
  {
    particpantId: 'PT_JPHXHZFZ',
    externalId: 78724,
    studyName: 'Congential Heart Defect',
    proband: 'no',
    biospecimenId: 'BS_42425',
    analyteType: 'DNA',
    tissueType: 'normal',
    ageAtSampleAcquisition: '40 years 4 days',
  },
  {
    particpantId: 'PT_JPHXHZFZ',
    externalId: 78724,
    studyName: 'Congential Heart Defect',
    proband: 'no',
    biospecimenId: 'BS_42425',
    analyteType: 'DNA',
    tissueType: 'normal',
    ageAtSampleAcquisition: '40 years 4 days',
  },
  {
    particpantId: 'PT_JPHXHZFZ',
    externalId: 78724,
    studyName: 'Congential Heart Defect',
    proband: 'no',
    biospecimenId: 'BS_42425',
    analyteType: 'DNA',
    tissueType: 'normal',
    ageAtSampleAcquisition: '40 years 4 days',
  },
  {
    particpantId: 'PT_JPHXHZFZ',
    externalId: 78724,
    studyName: 'Congential Heart Defect',
    proband: 'no',
    biospecimenId: 'BS_42425',
    analyteType: 'DNA',
    tissueType: 'normal',
    ageAtSampleAcquisition: '40 years 4 days',
  },
  {
    particpantId: 'PT_JPHXHZFZ',
    externalId: 78724,
    studyName: 'Congential Heart Defect',
    proband: 'no',
    biospecimenId: 'BS_42425',
    analyteType: 'DNA',
    tissueType: 'normal',
    ageAtSampleAcquisition: '40 years 4 days',
  },
  {
    particpantId: 'PT_JPHXHZFZ',
    externalId: 78724,
    studyName: 'Congential Heart Defect',
    proband: 'no',
    biospecimenId: 'BS_42425',
    analyteType: 'DNA',
    tissueType: 'normal',
    ageAtSampleAcquisition: '40 years 4 days',
  },
  {
    particpantId: 'PT_JPHXHZFZ',
    externalId: 78724,
    studyName: 'Congential Heart Defect',
    proband: 'no',
    biospecimenId: 'BS_42425',
    analyteType: 'DNA',
    tissueType: 'normal',
    ageAtSampleAcquisition: '40 years 4 days',
  },
];

export const mockColumns = [
  {
    Header: 'Participant ID',
    accessor: 'particpantId',
  },
  {
    Header: 'External ID',
    accessor: 'externalId',
  },
  {
    Header: 'Study Name',
    accessor: 'studyName',
  },
  {
    Header: 'Proband',
    accessor: 'proband',
  },
  {
    Header: 'Biospecimen ID',
    accessor: 'biospecimenId',
  },
  {
    Header: 'Analyte ID',
    accessor: 'analyteId',
  },
  {
    Header: 'Tissue Type',
    accessor: 'tissueType',
  },
  {
    Header: 'Age At Sample Acquiesition',
    accessor: 'ageAtSampleAcquisition',
  },
];
