export const REQUEST_MATCHING_LIST_OF_MEMBERS = 'REQUEST_MATCHING_LIST_OF_MEMBERS';

export const RECEIVE_MATCHING_LIST_OF_MEMBERS = 'RECEIVE_MATCHING_LIST_OF_MEMBERS';

export const REQUEST_MATCHING_LIST_OF_MEMBERS_ERROR = 'REQUEST_MATCHING_LIST_OF_MEMBERS_ERROR';

export const REQUEST_ROLES_FILTER_UPDATE = 'REQUEST_ROLES_FILTER_UPDATE';

export const REQUEST_INTERESTS_FILTER_UPDATE = 'REQUEST_INTERESTS_FILTER_UPDATE';

export const REQUEST_QUERYSTRING_UPDATE = 'REQUEST_QUERYSTRING_UPDATE';

export const REQUEST_CURRENTPAGE_UPDATE = 'REQUEST_CURRENTPAGE_UPDATE';

export const REQUEST_MEMBER_PER_PAGE_UPDATE = 'REQUEST_MEMBER_PER_PAGE_UPDATE';

export const REQUEST_STORE_RESET = 'REQUEST_STORE_RESET';
