export const REQUEST_MATCHING_LIST_OF_MEMBERS = 'REQUEST_MATCHING_LIST_OF_MEMBERS';

export const RECEIVE_MATCHING_LIST_OF_MEMBERS = 'RECEIVE_MATCHING_LIST_OF_MEMBERS';

export const REQUEST_MATCHING_LIST_OF_MEMBERS_ERROR = 'REQUEST_MATCHING_LIST_OF_MEMBERS_ERROR';
