export const REQUEST_MATCHING_LIST_OF_MEMBERS = 'REQUEST_MATCHING_LIST_OF_MEMBERS';

export const RECEIVE_MATCHING_LIST_OF_MEMBERS = 'RECEIVE_MATCHING_LIST_OF_MEMBERS';

export const REQUEST_MATCHING_LIST_OF_MEMBERS_ERROR = 'REQUEST_MATCHING_LIST_OF_MEMBERS_ERROR';

export const RECEIVE_TOTAL_MEMBERS_COUNT = 'RECEIVE_TOTAL_MEMBERS_COUNT';
