// DASHBOARD
export const FT_DASHBOARD = 'DASHBOARD';
export const FT_DASHBOARD_BANNER = 'DASHBOARD_BANNER';
export const FT_DASHBOARD_BANNER_TYPE = 'DASHBOARD_BANNER_TYPE';
export const FT_DASHBOARD_BANNER_MSG = 'DASHBOARD_BANNER_MSG';
export const FT_DASHBOARD_SAVED_QUERIES = 'DASHBOARD_SAVED_QUERIES';
export const FT_DASHBOARD_AUTHORIZED_STUDIES = 'DASHBOARD_AUTHORIZED_STUDIES';
export const FT_DASHBOARD_CAVATICA_PROJECTS = 'DASHBOARD_CAVATICA_PROJECTS';
export const FT_DASHBOARD_MY_PARTICIPANT_SETS = 'DASHBOARD_MY_PARTICIPANT_SETS';
export const FT_DASHBOARD_APACHE_ZEPPELIN = 'DASHBOARD_APACHE_ZEPPELIN';
export const FT_DASHBOARD_COVID_RESOURCES = 'DASHBOARD_COVID_RESOURCES';

// STUDIES
export const FT_STUDIES = 'STUDIES';

// Explore data
export const FT_EXPLORE_DATA = 'EXPLORE_DATA';

// Variant
export const FT_VARIANT = 'VARIANT';
export const FT_VARIANT_FACET_PARTICIPANT = 'VARIANT_FACET_PARTICIPANT';
export const FT_VARIANT_FACET_VARIANT = 'VARIANT_FACET_VARIANT';
export const FT_VARIANT_FACET_GENE = 'VARIANT_FACET_GENE';
export const FT_VARIANT_FACET_PATHOGENICITY = 'VARIANT_FACET_PATHOGENICITY';
export const FT_VARIANT_FACET_FREQUENTY = 'VARIANT_FACET_FREQUENTY';

// Community
export const FT_COMMUNITY = 'COMMUNITY';
