const ROUTES = {
  admin: '/admin',
  adminLegacy: '/admin_legacy',
  studies: '/studies',
  authRedirect: '/auth-redirect',
  cohortBuilder: '/explore',
  dcfRedirect: '/dcf_redirect',
  dashboard: '/dashboard',
  error: '/error',
  file: '/file',
  variant: '/variant',
  gen3Redirect: '/gen3_redirect',
  join: '/join',
  login: '/login',
  redirected: '/redirected',
  orcid: '/orcid',
  participant: '/participant',
  search: '/search',
  searchMember: '/memberPage',
  user: '/user',
  variantDb: '/variant',
  profile: '/profile',
  termsConditions: '/termsConditions',
};

export default ROUTES;
